- name: install and run nginx
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
