- name: variables from arguments
  hosts: localhost
  tasks: 
  - name: get from arguments 
    ansible.builtin.debug:
      msg: "i am learning {{Course}} from Trainee {{Trainer}} with duration of {{Duration}}."