- name: loops
  hosts: localhost
  tasks:
  - name: print os's
    ansible.builtin.debug:
      msg: "Hello, {{item}}"
    loop:
    - linux
    - windows
    - ios
- name: install packages
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.apt:
      name: "{{item}}"
      state: latest
    loop:
    - nginx
    - mysql
    - jdk-17